package com.commerce.fashion.enums;

public enum UserResponse {
    SUCCESS,
    ACCOUNT_DOESNOT_EXIST_CREATE_AN_ACCOUT,
    ACCOUNT_ALREADY_EXISTS,
    FAILED,
    PASSWORD_AND_CONFIRMPASSWORD_DOESNT_MATCH,
    INCORRECT_PASSWORD;
}
